-- Org-scoped CORS allowlist for the new public-API-per-module pattern
-- (ADR-0008, Standards §12): every external-site-facing API endpoint checks
-- the request's Origin header against this column before doing anything
-- else, instead of a hardcoded per-module/per-client CORS list.
--
-- text[] rather than a single text column: a client's site commonly needs
-- more than one trusted origin at once (production domain + a staging/
-- preview domain, or a bare domain plus its www subdomain) and there's no
-- reason those variants share a single string. A single-origin column would
-- force an artificial choice or a later migration the moment a second
-- domain shows up — building the array in from the start avoids both.
--
-- Nullable, no backfill of real domains here: this is provisioned per
-- client as their actual site domain(s) become known (Standards §12 —
-- set at provisioning time going forward), not guessed at migration time.
-- Existing organizations (Netbreakerz, WorldView, ...) get their real
-- origin(s) filled in via a follow-up, targeted update once each site's
-- domain is confirmed, not a blanket backfill here.
alter table public.organizations add column allowed_origins text[];
